import {
  Music,
  Music2,
  Calendar,
  ShoppingBag,
  Video,
  BookOpen,
  GraduationCap,
  Code,
  Mail,
  Palette,
  Camera,
  Globe,
  Image as ImageIcon,
  Briefcase,
  AtSign,
  Link as LinkIcon,
  Sparkles,
  BarChart3,
  Smartphone,
  Zap,
  ShieldCheck,
  PenLine,
  Type,
  ScanLine,
  Gem,
  Eye,
  MousePointerClick,
  Users,
  TrendingUp,
  UserPlus,
  Share2,
  Play,
  type LucideIcon,
} from "lucide-react"

const map: Record<string, LucideIcon> = {
  music: Music,
  spotify: Music,
  "apple-music": Music2,
  tiktok: Video,
  calendar: Calendar,
  "shopping-bag": ShoppingBag,
  youtube: Play,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  github: Code,
  mail: Mail,
  palette: Palette,
  instagram: Camera,
  globe: Globe,
  video: Video,
  camera: Camera,
  image: ImageIcon,
  linkedin: Briefcase,
  twitter: AtSign,
  link: LinkIcon,
  sparkles: Sparkles,
  "bar-chart-3": BarChart3,
  smartphone: Smartphone,
  zap: Zap,
  "shield-check": ShieldCheck,
  "pen-line": PenLine,
  type: Type,
  "scan-line": ScanLine,
  gem: Gem,
  eye: Eye,
  "mouse-pointer-click": MousePointerClick,
  users: Users,
  "trending-up": TrendingUp,
  "user-plus": UserPlus,
  "share-2": Share2,
}

export function Icon({
  name,
  className,
}: {
  name: string
  className?: string
}) {
  const Cmp = map[name] ?? Globe
  return <Cmp className={className} aria-hidden="true" />
}
